### ISSUE TITLE
How does MMDetection3D collect the results of val_step?

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#1122]
Hi, 
Thanks for the great work of OpenMMLab.
I am working on a customized task based on MMDetection3D recently. 
In order to conduct evaluation after each training epoch, I guess I need to collect the output of each val_step 
(https://github.com/open-mmlab/mmcv/blob/e4b5348ebf407f0886bc11caa7ca74d2fbf693ac/mmcv/runner/epoch_based_runner.py#L32)
After that, I can get the evaluation results based on the collected results.

My question is:
where I can access the outputs of `val_step` in MMDetection3D to collect them? 
and where I should call my customized evaluation code to process the collected outputs?

**Comment by Tai-Wang** [comment]
Typically you do not need to care about the overall training logistic, runners and hooks because they are maintained well in the mmcv and mmdet. To evaluate your customized tasks on your dataset, you just need to define the format and evaluation part in your `Dataset class` like [kitti_dataset.py](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/kitti_dataset.py). The results of detectors will be passed into the evaluation API automatically if you follow the standard definition.
