### ISSUE TITLE
Minor issue in FCOS3D

### ISSUE THREAD

**Issue by prismformore** [open-mmlab/mmdetection3d#1126]
https://github.com/open-mmlab/mmdetection3d/blob/30ad1aae13fe78e5b91d6d6f9eee835c1c086612/mmdet3d/models/dense_heads/fcos_mono3d_head.py#L438

Hello! Here, when "pos_inds" is empty (suggested by the "else" condition), all losses calculated here should all be zero by nature and make no sense. 

Here probably we want all pixel values to be zero? For example we could replace the offset loss calculation with:
`loss_offset = flatten_bbox_preds[:, :2].sum()`

**Comment by Tai-Wang** [comment]
That "else" is just a workaround to deal with the case when there are no positive predictions. We need to set all the losses to zero and get zero gradients propagated back. Otherwise, there will be variables not involved in the backpropagation and trigger errors (or get halted I do not remember clearly). In a word, this is a typical way to deal with the corner case instead of a bug.

**Comment by prismformore** [comment]
> ons. We need to set all the losses to zero and get zero gradients propagated back. Otherwise, there will be variables not involved in the backpropagation and trigger errors (or get halted I do not remember clearly). In a word, this is a typical way to deal wi

Good to know. Thanks a lot.
