### ISSUE TITLE
How to visualize the input and detection during trainng or evaluation

### ISSUE THREAD

**Issue by chyohoo** [open-mmlab/mmdetection3d#1167]
Hi, 
Thanks for the fascinating work of mm3d.
I want to know if it is possible to use a custom hook to visualize the input point cloud, detection output, or the internal feature maps through tensorboard?
Thanks.

**Comment by ZCMax** [comment]
The high-level hooking apis provided by `mmcv` can only be invoked before/after an iteration/epoch. If you want to visualize the internal feature maps instead of final outputs, you may need to modify the forward method to return the feature map, and then use the hooking apis in `mmcv`. Or you can just use PyTorch's built-in low-level hooks.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
