### ISSUE TITLE
Cannot download the pretrained model by aliyun

### ISSUE THREAD

**Issue by niezhongliang** [open-mmlab/mmdetection3d#13]
Hi, 
Following the instruction, I am trying to download the SECOND pretrained model to test KITTI Dataset. However, I cannot download it by simply replacing the aws url with aliyun url. 

Are there any suggestions?

Below is AWS url: 
https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection3d/v0.1.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

I modified it to:
https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection3d/v0.1.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
(failed to download)

Thanks

**Comment by ZwwWayne** [comment]
Hi @niezhongliang ,
For a quick workaround, please use `https://openmmlab.oss-accelerate.aliyuncs.com/` to replace `https://open-mmlab.s3.ap-northeast-2.amazonaws.com`, e.g., https://openmmlab.oss-accelerate.aliyuncs.com/mmdetection3d/v0.1.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth. The bug will be fixed in https://github.com/open-mmlab/mmdetection3d/pull/14.
