### ISSUE TITLE
Question regarding VoxelNet and SECOND!

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#1375]
I have a question regarding the SECOND model which is based on voxelnet. After looking into a configuration file `/mmdetection3d/blob/master/configs/_base_/models/hv_second_secfpn_kitti.py` the voxel_encode is HardSimpleVFE but it doesn't mention the number_of_layers (VFE-layer) to be used. Such as in SECOND and Voxelnet,  2-layers of VEF-1(16,32) and VEF-1(32,64) are mentioned in the paper. I will really appreciate it if someone explains why it's not explicitly mentioned in the code.

Also, if I want to use the simple 3D convolution which is in original work of voxelnet instead of SparseEncoder, is there any implementation available in the codebase ?

Thanks

**Comment by Tai-Wang** [comment]
1. The implementation of the voxel encoder is simplified after the SECOND paper is published. You can refer to its official codebase and we just keep its released version.
2. 3D convolution can yield much more computational overhead. We do not provide this version of implementation because this is really inefficient in practical use.

**Comment by ammaryasirnaich** [comment]
@Tai-Wang much appreciated the response. Please can you confirm if there is any difference between the implementation or the concept of Anchor3DHead from the official codebase ?

**Comment by ammaryasirnaich** [comment]
I think i have solved the issue.
