### ISSUE TITLE
mmdet3d/core/evaluation/kitti_utils/eval.py

### ISSUE THREAD

**Issue by Shanyaodedanshen** [open-mmlab/mmdetection3d#1464]
function calculate_iou_partly() return overlaps, parted_overlaps, total_gt_num, total_dt_num. Why when call this function, get the return value: overlaps, parted_overlaps, total_dt_num, total_gt_num?

**Comment by Tai-Wang** [comment]
This is a legacy issue. Because the iou calculation is a symmetric function for dt and gt, the input/output of dt and gt can be exchanged. You can find both the input and output of that function exchange these two variables when using it during evaluation. It does not affect the result for now, but we will consider fixing it in the future to avoid more confusion.

**Comment by Tai-Wang** [comment]
@VVsssssk Please note this problem during future refactoring.

**Comment by VVsssssk** [comment]
Thx for your issue. I will fix it in refactor version.
