### ISSUE TITLE
kitti_eval can't handle no annotation file

### ISSUE THREAD

**Issue by YinengXiong** [open-mmlab/mmdetection3d#1478]
**Describe the bug**

I'm trying to convert nuscenes data to KITTI format and run mono3d training

when the code running  `kitti_eval` in   `mmdet3d/core/evaluation/kitti_utils/eval.py`, it seems the function cannot handle an image with 0 GT annotations
https://github.com/open-mmlab/mmdetection3d/blob/76e351a7a6b0b83d7dc729bdfee5f17743c72f76/mmdet3d/core/evaluation/kitti_utils/eval.py#L717

but there are some frames in nuscenes without annotation so the code reports some error during validation
Is this situation within expectation?

**Comment by Tai-Wang** [comment]
We didn't try to convert nuScenes to KITTI before. I can provide some hints to you and hope they can help you understand this situation:
- Typically we prefer to filter those images without GT annotations in mmdet3d.
- This line is designed to avoid evaluating AOS when using KITTI metrics on Waymo because Waymo is a multi-camera setting. The computation of alpha is related to which image the bbox is located in.

**Comment by KangHyunwoogi** [comment]
hello, thanks for detailed situation description about error.
I'm in completely same situation with you.. I guess this error is from my dataset which don't include image and calib.
If you have solved this problem, may I know how you solved it?

**Comment by selmadeac** [comment]
> hello, thanks for detailed situation description about error. I'm in completely same situation with you.. I guess this error is from my dataset which don't include image and calib. If you have solved this problem, may I know how you solved it? thanks

Same issue encountered for waymo dataset. I added one line of code and seems to work:
