### ISSUE TITLE
The meaning of P matrices in KITTI calibration

### ISSUE THREAD

**Issue by Steven-m2ai** [open-mmlab/mmdetection3d#1491]
Hello, reading mmdetection3D's documentation, "P2: camera2 projection matrix after rectification, an 3x4 array".
So if I understand this correctly, does this mean `P2 = K * [R|t]`? Where `K` is the intrinsic and `[R|t]` is the extrinsic matrices? This would lead to it being 3x4. 

However, when i read "after rectification", doesn't that mean that we are already in camera coordinate system? by which we only need the intrinsic matrix `K`? But `K` is 3x3. 

Another theory i have is that it might be [K|t] where t is the center of the world coordinate in camera coordinate perspective.

Any ideas? Thank you for your time!

**Comment by Tai-Wang** [comment]
The P2 in KITTI can be regarded as the projection matrix from the referenced camera (xyz) to image 2 (uvd). It is not a pure intrinsic matrix because it involves the translation/rotation transformation between the referenced camera and camera 2. You can refer to its [original paper](http://www.cvlibs.net/publications/Geiger2013IJRR.pdf) for more details.

**Comment by Steven-m2ai** [comment]
thank you for this explanation. I have referenced the original paper, and can now draw the connection.
