### ISSUE TITLE
FCOS3D Bounding Box calculation and prediction

### ISSUE THREAD

**Issue by Kwame261** [open-mmlab/mmdetection3d#1509]
Hello I would like to know how the  Bounding  boxes are are calculated.
1. How are the bounding boxes predicted?
2. For instance how are the confidence scores assigned given multiple bounding box predictions for an object..
3. Given an Object like a car that is partially covered, Does it  predict the full dimensions of the car or the part  that is visible.

Thank You!

**Comment by Tai-Wang** [comment]
1. We predict its projected center, depth, 3D size, and rotation and then reconstruct the 3D box in 3D space.
2. The classification score is just in one-hot format, 1 for the correct class and 0 for others. The centerness score follows the Gaussian Distribution presented in the paper.
3. We would predict the full dimension of the car because we only have that annotation.

**Comment by Kwame261** [comment]
Thank  You!From: Tai-WangSent: Saturday, May 28, 2022 11:22 PMTo: open-mmlab/mmdetection3dCc: Kapo001; AuthorSubject: Re: [open-mmlab/mmdetection3d] FCOS3D Bounding Box calculation and prediction (Issue #1509) We predict its projected center, depth, 3D size, and rotation and then reconstruct the 3D box in 3D space.The classification score is just in one-hot format, 1 for the correct class and 0 for others. The centerness score follows the Gaussian Distribution presented in the paper.We would predict the full dimension of the car because we only have that annotation.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
