### ISSUE TITLE
Is there a way to save the augmented data within the training pipeline to enable future visualization?

### ISSUE THREAD

**Issue by heming7** [open-mmlab/mmdetection3d#1630]
I am training a 3D detection model on NuScenes dataset and I have applied data augmentation in the training pipeline. I would like to know is there a way that I can somehow save the augmented data so that I can use the render_pointcloud_in_image from the nuscenes-devkit to visualize the projection of lidar points onto images after data augmentation.

**Comment by ZCMax** [comment]
Sorry for the late reply, for now, we provide the `browse_dataset.py` script which can visualize the augmented data in the training pipeline, more details can be seen in https://github.com/open-mmlab/mmdetection3d/blob/master/tools/misc/browse_dataset.py.  Because mmdet3d store point clouds and images in an object named DataContainer so you can take your point cloud and image after augment by: https://github.com/open-mmlab/mmdetection3d/blob/c8347b7ed933d70fcfbfb73a3541046b8c8e8f5e/tools/misc/browse_dataset.py#L110
https://github.com/open-mmlab/mmdetection3d/blob/c8347b7ed933d70fcfbfb73a3541046b8c8e8f5e/tools/misc/browse_dataset.py#L147
then continue to process convert torch to numpy and save it.
