### ISSUE TITLE
Question for construct pillar on pillar_encoder.py 

### ISSUE THREAD

**Issue by rasd3** [open-mmlab/mmdetection3d#165]
**Bug fix**
https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/voxel_encoders/pillar_encoder.py#L124
Since line f_center get features[:, :, 2] value by reference not copy, point clouds coordinates are overwritten by distance from pillar center. Eventually on line 138, features[:, :, :2] is identical with features[:, :, 7:9]
I don't think it was intended. please check (I think f_center = features[:, :, :2].clone() should be appropriate)

**Comment by rasd3** [comment]
I find if self.legacy is False pillar_encoder operate properly. Can you explain about why duplicate f_center?

**Comment by ZwwWayne** [comment]
The legacy means the legacy implementation, in the original PointPillar implemented in SECOND.PyTorch, the features are indeed overwritten, but it is fine because `self.legacy=True` achieves the performance on KITTI. If `self.legacy = False`, it means this bug is fixed and this is used in nuScenes dataset.
