### ISSUE TITLE
Why not stack the tensors(like point clouds) along batch-dimension?

### ISSUE THREAD

**Issue by zheyuanWang** [open-mmlab/mmdetection3d#1678]
Take point cloud tensor as an example: 

for batch_size = 2, we have two tensors that store point clouds: 

`pcd1` with shape `[1000, 4]` and `pcd2` with shape `[1050, 4]`.

Instead of stacking tensors in batch dimension like [OpenPCDet](https://github.com/open-mmlab/OpenPCDet), mmdetection3d organize them in to a list `[pcd1, pcd2]`. 

During forwarding, the list would be calculated via a **for-loop**, which I believe is slower than processing a stacked tensor with shape `[2, 1050, 4]` (i.e. `[Batch_size, max_points_number, num_feature]`)
```
    for res in points:
            res_voxels, res_coors, res_num_points = self.pts_voxel_layer(res)
            voxels.append(res_voxels)
            coors.append(res_coors)
            num_points.append(res_num_points)
```
There would be extra time need for padding up the point clouds to the same length before stacking. I am wondering whether the **for-loops**  all over the network consume less time than stacking the tensor first.

> ps. I am using a config file similar to `configs/centerpoint/centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_kitti.py`

**Comment by Tai-Wang** [comment]
Actually, this is overall a trade-off of efficiency and memory overhead. The padding operation will sacrifice more memory to save some padded input while the list manner can not avoid for-loop when extracting features afterward. From my opinion, this will not have much influence on the overall efficiency because the bottleneck for each forward is not here. However, if using the padding operation, that will have trouble when two samples have very different point numbers. This is harmful to the code's robustness.
