### ISSUE TITLE
Why the KITTI Cyclist_2D_AP40 in pgd always lower than smoke?

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection3d#1713]
but car and pedestrian seems better for pgd ; cyclist sample nums is the lowest in KITTI

**Comment by clw5180** [comment]
I see in MV-FCOS++ :"The cyclist performance of FCOS3D++ is much lower possibly because the strong uncertainty filters out too many positive predictions". How to solve this problem in pgd? Thanks

**Comment by Tai-Wang** [comment]
It's hard to say how to improve the performance only for cyclists on KITTI because its performance is always unstable, but you can have more attempts on Waymo (relatively stable from my observation).

I believe it is related to the depth loss design because the current design will yield a very strong uncertainty indicator such that it will filter too many cyclists predictions to guarantee a good precision (yet bad recall). We try smoothL1 loss as nuScenes before and it can bring a little gain to cyclist performance while drag down the performance of other classes. So a better approach can be expected to deal with this case.

**Comment by clw5180** [comment]
Thanks!
