### ISSUE TITLE
NuImages models' output int classes do not match str labels

### ISSUE THREAD

**Issue by aleksandrkim61** [open-mmlab/mmdetection3d#172]
Thank you for working on detection models for NuImages!

I've tried using a couple of them on pictures from NuImages following the synchronous code [here](https://mmdetection.readthedocs.io/en/latest/getting_started.html#high-level-apis-for-testing-images) without any changes. The output images have good detections/segmentations but the labels are incorrect. It looks like the [0-10] int labels do not match string labels in the models' `CLASSES` field [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/nuim_instance.py).
I have tried two models: `cascade_mask_rcnn_x101_32x4d_fpn_1x_nuim.py` and `mask_rcnn_r101_fpn_1x_nuim.py`
![result_n015-2018-07-16-11-49-16+0800__CAM_FRONT__1531713370862460](https://user-images.githubusercontent.com/17831342/96444707-06a1ab80-120f-11eb-9096-8c9d137a34fa.jpg)
![result](https://user-images.githubusercontent.com/17831342/96445301-f8a05a80-120f-11eb-8e5f-2b9d8d5c1d0c.jpg)

Unrelated:
What is the reasoning to include NuImages configs in MMDetection3D instead of MMDetection? 
These models/configs only operate on 2D images and might be more suitable for the 2D detection repository. I am guessing this was done to reuse NuScenes files you have for 3D models. 
If you intend on keeping it this way, perhaps it would be good to mention this in the README so new users will use the 2D API to work with these models? As a first-time user, I initially looked into documentation for the 3D API.

**Comment by ZwwWayne** [comment]
1. We also find the label order issue. It will be fixed in this PR https://github.com/open-mmlab/mmdetection3d/pull/155/. Since the model is trained in a different order, we will release new models in the model zoo for that.
2. Why include NuImages configs in MMDetection3D instead of MMDetection: simply because it is only related to configs and scripts, so it is fine to put it in either mmdet/mmdet3d. One advantage to put it in mmdet3d is it can be beneficial for models on nuScenes dataset.
3. Thanks for your kind suggestions. We will enhance the documentation in the next release. Meanwhile, PRs are also welcomed.

**Comment by nmll** [comment]
Have you seen the model occupy more and more memory when running the cascade_mask_rcnn_x101_32x4d_fpn_1x_nuim.py model?

**Comment by aleksandrkim61** [comment]
If you are asking me:

I did not monitor resources when running it, so cannot tell you for sure.
 
Nevertheless, I do not think there is any reason for the model to retain anything in memory between runs. Perhaps, you should check if you have memory leaks elsewhere in your code? Storing intermediate results in global variables or maintaining metrics for logging could be a culprit.
