### ISSUE TITLE
Anchor3DRangeGenerator

### ISSUE THREAD

**Issue by holtvogt** [open-mmlab/mmdetection3d#1720]
I'm wondering why the `z` values within  `ranges` differ from the `point_cloud_range`.

- Why `-0.6` for pedestrians/cyclists and `-1.78` for cars? 
- Do I have to choose these values for my custom (KITTI-based) dataset as well?

Seen, e.g. here:
https://github.com/open-mmlab/mmdetection3d/blob/073f353cf21d31beabcbffa45bef10a6f81abff3/configs/_base_/models/hv_pointpillars_secfpn_kitti.py#L41

**Comment by ZCMax** [comment]
Please refer to this issue:https://github.com/open-mmlab/mmdetection3d/issues/986

**Comment by holtvogt** [comment]
So, as far as I understand, the `z` values should match the `z` position of my ground area in my recordings?

**Comment by Tai-Wang** [comment]
Should match the average height of object centers.

**Comment by ste-wit** [comment]
Since I am currently training SECOND and PointPillars on a custom dataset, I am also curious how to choose/adjust the settings for the Anchor3DRangeGenerator.

@Tai-Wang You mentioned that the z-coordinate should match the average height of object centers. Now, the Velodyne sensor in the KITTI setup is positioned at z = 1.73m (see [setup](https://www.cvlibs.net/datasets/kitti/setup.php)). If this coordinate system is used for training, this would mean that the object centers relative to the ground are:
- Pedestrians / Bicycles: z = 1.73m + (-0.6m) = 1.13m
- Cars: z = 1.73m + (-1.78m) = -0.05m

Furthermore, if we now compute the bottom center of these bounding boxes by taking the anchor box [dimensions](https://github.com/open-mmlab/mmdetection3d/blob/9556958fe1c6fe432d55a9f98781b8fdd90f4e9c/configs/_base_/models/hv_pointpillars_secfpn_kitti.py#L45) into account, I end up with:
- Pedestrians / Bicycles: z = 1.13m - 1.73m/2 = 0.265m
- Cars: z = -0.05m - 1.56m/2 = -0.83m

Is this correct? To me it seems that the anchor z ranges for pedestrians and bicycles are correct but off for cars. If the object center is used, I would expect for cars a z offset of `(1.56m/2) - 1.73m = -0.95m` and not `-1.78m`.
