### ISSUE TITLE
Is there a plan to include Complex-YOLO?

### ISSUE THREAD

**Issue by shanmo** [open-mmlab/mmdetection3d#1731]
[Complex-YOLO](https://arxiv.org/abs/1803.06199) is a fast single stage 3D object detection method, is there a plan to include it as well?

**Comment by ZCMax** [comment]
Thank you for your suggestion, but Complex-YOLO is currently not in our short-term plan. Contributions are welcome.

**Comment by Tai-Wang** [comment]
Sorry for the late reply due to the recent busy refactoring. It is definitely great if you are willing to integrate this repo to mmdet3d. As for your question, if YOLO in mmdet is similar to some implementation in Complex-YOLO, it would be much better to leverage it to ease the burden of the migration. We also encourage this because it is one of the motivation/advantage to building mmdet3d on top of mmcv and mmdet.
