### ISSUE TITLE
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=1.5.2, <=1.7.0.

### ISSUE THREAD

**Issue by dk-liang** [open-mmlab/mmdetection3d#1761]
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=1.5.2, <=1.7.0.

![image](https://user-images.githubusercontent.com/23117298/186354559-27205b63-640c-4862-a6bd-5ec9f5cb71cd.png)

when I try pip install mmcv==1.5.2
It shows:

![image](https://user-images.githubusercontent.com/23117298/186354148-688bedd9-3b6e-4fc2-a4d4-d9f2896d070e.png)

**Comment by ZCMax** [comment]
The second error is reported by mmdetetection, you need to install the correct mmcv and mmdet version according to our doc

**Comment by carlinds** [comment]
mmdetection and mmsegmentation seems to require different versions of mmcv, and there is no version that satisfies both.
mmdet seems to require mmcv>=1.5.2, <=1.7.0, while mmseg requires mmcv>=(1, 3, 13, 0, 0, 0), <=(1, 5, 0, 0, 0, 0).
Both mmdet and mmseg are installed in the provided docker image, but fails for different asserts depending on which mmcv-version is chosen.

How should one solve this? Since no mmcv version while satisfy both dependencies included in this environment.

The provided demo is not possible to run due to this:
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

**Comment by JingweiZhang12** [comment]
Hi,  the latest `mmseg` requires mmcv>=`'1.3.13'` <`1.7.0`. https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/__init__.py#L9.
Suggest that you can create a new issue and use the issue template.

**Comment by lcc815** [comment]
shenme wanyier
