### ISSUE TITLE
bugs about RandomFlip3D

### ISSUE THREAD

**Issue by AndyYuan96** [open-mmlab/mmdetection3d#1815]
I use mmdet3d 1.0, I find that when I set flip_ratio_bev_horizontal=0, flip_ratio_bev_vertical=1, the flag 'flip' in input_dict when training is false, only when I set flip_ratio_bev_horizontal > 0, the flag 'flip' is set to true.

**Comment by Tai-Wang** [comment]
flip should be False when flip_ratio_bev_horizontal=0, flip_ratio_bev_vertical=1 because the vertical flip means the flip of front and back. It is only used for point cloud augmentation while the flip is an attribute recording the status of images. So we only change the flip to True when the horizontal flip is conducted.
