### ISSUE TITLE
Why `origin=(0.5, 0.5, 0.5)` in `CameraInstance3DBoxes` for KITTI dataset

### ISSUE THREAD

**Issue by tuan97ta** [open-mmlab/mmdetection3d#1867]
In file `datasets/kitti_mono_dataset.py` .I want to know `origin=(0.5, 0.5, 0.5)` in `CameraInstance3DBoxes` for KITTI dataset.
Because , I found : 
- In file label `002799.txt` : `Pedestrian 0.00 0 2.81 721.17 155.47 791.65 297.36 1.75 0.43 0.99 1.96 1.44 9.01 3.02`
   --> Center xyz = `1.96 1.44 9.01`
- I generate Dataloader with file config `config/_base_/datasets/kitti-mono3d.py` , I get : 
   `gt_bboxes_3d: tensor([[-2.0247,  0.5650,  9.0100,  0.9900,  1.7500,  0.4300,  0.1216]],device='cuda:0')`
   --> Center xyz = `-2.0247,  0.5650,  9.0100`
Two `xyz` value is diffirenct .

**Comment by JingweiZhang12** [comment]
In the branch dev-1.x, the origin of `CameraInstance3DBoxes` is (0.5, 1.0, 0.5).

**Comment by Tai-Wang** [comment]
It's because the master version still uses the coco-style json info, which stores the object "real center" in "cam2", while we usually use the "bottom center" in "cam0". So they are different as you mentioned. We have unified them into one info in the latest 1.x branch, and take the latter as the default convention.
