### ISSUE TITLE
Bug in resize - RandomFlip3D pipeline

### ISSUE THREAD

**Issue by emc222** [open-mmlab/mmdetection3d#1926]
In a resize - RandomFlip3D pipeline as [https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pgd/pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d.py#L77](url)
resize change 'img_shape' after resize img in [https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L242](url)
but in RandomFlip3D when modify centers2d and cam2img the 'ori_shape' is used [https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/transforms_3d.py#L137](url)
this causes misalignment especially when resize shape differs much with ori_shape, is this a bug?

**Comment by ZCMax** [comment]
Yes, it's a bug, which has been fixed in our  dev-1.x branch, please refer to  https://github.com/open-mmlab/mmdetection3d/blob/c4bc2f31692628270d0b21d80a1743a161be4eba/mmdet3d/datasets/transforms/transforms_3d.py#L175,  we will fix the bugs in master/dev branch soon, and compare the performance difference
