### ISSUE TITLE
Confusing with nuscenes_dataset.format_result()

### ISSUE THREAD

**Issue by YeungLy** [open-mmlab/mmdetection3d#198]
Hi, thanks for your great work!

I'm just confusing about the evaluation process on nuscenes dataset.
```python
def evaluate(self,
                 results,
                 ...):
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
    .....
```
the argument `results` is the output of model, which is a list of dict : `[{'boxes_3d': ..., 'labels_3d': ..., 'scores_3d': ... }, {...},]`

In `self.format_results()`,  the code is:
```python
def format_results(self, results, ...):
    if not isinstance(results[0], dict):
        result_files = self._format_bbox(results, jsonfile_prefix)
    else:
        result_files = dict()
        for name in results[0]:
            print(f'\nFormating bboxes of {name}')
            results_ = [out[name] for out in results]
            tmp_file_ = osp.join(jsonfile_prefix, name)
            result_files.update(
                    {name: self._format_bbox(results_, tmp_file_)})
    .....
```
Seems like it makes sure the argument `results` passed to `self._format_bbox()` is a list of list instead of a list of dict,  which is inconsistent with the description at `self._format_bbox()`.  
**Problem**: Wrong format of `results` makes calling 'output_nusc_box()' failed.

```python
def _format_bbox(self, results, jsonfile_prefix=None):
    """Convert the results to the standard format.
    Args:
         results (list[dict]): Testing results of the dataset.
    """
    for sample_id, det in enumerate(mmcv.track_iter_progress(results)):
        annos = []
        boxes = output_to_nusc_box(det)  #failed here. det should be a dict has 3 keys ['boxes_3d', 'labels_3d', 'scores_3d']
```

I am not sure if I understand the code properly or is there any material to reference?
Btw, I use the same dataset config as `nusc_3d.py` , but setting `LoadFromMultiSweeps.sweep_num=0` since I didnt download sweep subsets of nuscenes and just want to use keyframe. Is it may cause this error?

**Comment by Tai-Wang** [comment]
Actually, taking the single-modal methods like LiDAR-based detectors as an example, the argument `results` is not simply the format as you think. It is like `[{'pts_bbox': {'boxes_3d': ..., 'labels_3d': ..., 'scores_3d': ... }}, {...},]` instead of `[{'boxes_3d': ..., 'labels_3d': ..., 'scores_3d': ... }, {...},]`, which is convenient for the model to output different types of predictions.

As for the case without using multisweeps, I have not tried on this codebase before. But I guess it is ok if you train the detectors smoothly. From my previous experience, models trained with only keyframes would just have a degraded performance.

**Comment by YeungLy** [comment]
Thanks! I checked the code at model.simple_test() and found that there was different output format between using KITTI and Nuscenes. And I just assumed the format of `results`  is same as using KITTI.
