### ISSUE TITLE
question about kitti evaluation

### ISSUE THREAD

**Issue by tyjiang1997** [open-mmlab/mmdetection3d#200]
hi~, I noticed that two mAP values are provided in the[ config ](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/3dssd)of 3DSSD, one is the result of mmdet3d and the other is the official result of KITTI , the accuracy of which is quite different. Do you provide official methods of evaluation? Because I recently reproduced PV-RCNN on MMDET3D, the evaluation result of mmdet3d  is 80.72, but in the official implementation of PV-RCNN, the accuracy is 83.61. So I wonder if they will be measured differently.

**Comment by Tai-Wang** [comment]
Generally speaking, most of codebases/papers for 3D detection use the same evaluation protocol/codes as ours and 3DSSD is just a minority. So don't worry about that. It is fair and reasonable to validate it with our implemented evaluation methods.

A hint for PV-RCNN results on KITTI is that there exist sharp changes in the results on the validation set due to the limited size of dataset. You can simply train/evaluate it more times with different random seeds and see whether it could achieve the reported performance as the official implementation.

If you finally make it, PRs are welcome.
