### ISSUE TITLE
how to train Part-A2 on nuscenes

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection3d#237]
Hi, sir. It is a nice work! I want to train Part-A2 network on nuscenes dataset but I have no idea how to do it (convert nuscenes dataset to kitti format using [export_kitti.py](https://github.com/nutonomy/nuscenes-devkit/blob/02e9200218977193a1058dd7234f935834378319/python-sdk/nuscenes/scripts/export_kitti.py) will lose a lot of information because it only support converting nuScenes images from CAM_FRONT to KITTI format), can you share me some advice? Very appreciate for your reply!!

**Comment by Tai-Wang** [comment]
You do not need to generate data information like KITTI, because we support nuScenes data reorganization.
So the core problem is to modify the PartA2 [config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.py) to fit the nuScenes setting. Basically there are two parts to be modified, dataset related and model hyperparameters. For the former part, you can refer to this dataset [config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/nus-3d.py) while for the latter part, you may need to refer to other models for nuScenes like [SSN](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/ssn/hv_ssn_secfpn_sbn-all_2x16_2x_nus-3d.py) and [PointPillars](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_sbn-all_4x8_2x_nus-3d.py) and adjust related settings accordingly.

**Comment by yustaub** [comment]
thanks, I will try it.
