### ISSUE TITLE
How can I train a single model for Pedestrian or Cyclist in WOD?

### ISSUE THREAD

**Issue by Lzc6996** [open-mmlab/mmdetection3d#314]
I am trying to train a single class model for Pedestrian or Cyclist. I modify the `configs/_base_/datasets/waymoD5-3d-car.py`  into 
`class_names = ['Pedestrian'],  prepare=dict(filter_by_difficulty=[-1], filter_by_min_points=dict(Pedestrian=10)), sample_groups=dict(Pedestrian=10)`
But it don't lead the right results.

**Comment by Tai-Wang** [comment]
Please also modify the configs for model, instead of just configs for dataset like `configs/_base_/datasets/waymoD5-3d-car.py`. For example, you can refer to the base model [config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_pointpillars_secfpn_waymo.py) and specific model [config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py) for single class (car). For your case, at least you need to change the anchor setting.

**Comment by Lzc6996** [comment]
@Tai-Wang Thanks, I'll try it again

**Comment by Lzc6996** [comment]
@Tai-Wang 
I modify the models' config, the loss looks right. Thanks for your help.
