### ISSUE TITLE
Some error outputs while using roiware_pool3d operations

### ISSUE THREAD

**Issue by HilbertXu** [open-mmlab/mmdetection3d#315]
Hey guys,

Thanks for your amazing work!
I am trying to use your roiaware_pool3d operations in my project. However I found that the output of points_in_boxes_gpu function looks incorrect.

I input 3D point clouds and bounding boxes([x, y, z, l, w, h, rz]) in lidar coordinates, but the outputs of point_in_boxes_gpu seem to be rotated in a wrong angle.

I will attach some output here, hoping it will help you to figure out my error.

<img width="965" alt="Screen Shot 2021-02-22 at 4 33 01 PM" src="https://user-images.githubusercontent.com/33152255/108683468-998b8300-752c-11eb-9849-f773dec92c3d.png">
<img width="1016" alt="Screen Shot 2021-02-22 at 4 37 14 PM" src="https://user-images.githubusercontent.com/33152255/108683482-9db7a080-752c-11eb-8372-233c1820f140.png">

**Comment by THU17cyz** [comment]
@HilbertXu 

Hi, thanks for your interest in mmdet3d. I checked the functions and found that according to [the definition of the LIDAR coordinate system](https://github.com/open-mmlab/mmdetection3d/blob/8214a9779997ad3606a4830a7b718ba1bcfbf16d/mmdet3d/core/bbox/structures/lidar_box3d.py#L13), _point_in_boxes_gpu_ does rotate the bbox using the wrong angle. 

Unfortunately, this is a legacy issue because earlier we followed the coordinate system convention of [SECOND](https://github.com/traveller59/second.pytorch). Due to the large amount of code related with this issue, we cannot simply fix _point_in_boxes_gpu_. We are planning a refactor of the coordinate systems to resolve this issue. Sorry for the inconvenience.

As you mentioned, you were only using the CUDA ops, so a quick fix could be taking the opposite of the rotation angle in the CUDA ops in _your_ code.

For example:

```python
boxes = torch.tensor(
    [[[0.0, 0.0, 0.0, 1.0, 20.0, 1.0, 0.523598]]], dtype=torch.float32).cuda() # 30 degrees
pts = torch.tensor(
    [[[4, 6.928, 0], [6.928, 4, 0], [4, -6.928, 0], [6.928, -4, 0],
      [-4, 6.928, 0], [-6.928, 4, 0], [-4, -6.928, 0], [-6.928, -4, 0]]], dtype=torch.float32).cuda()  
point_indices = points_in_boxes_gpu(points=pts, boxes=boxes)
print(point_indices)
```

The original output is 

```python
tensor([[ 0, -1, -1, -1, -1, -1,  0, -1]], device='cuda:0', dtype=torch.int32)
```

Take the opposite of _rz_ [here](https://github.com/open-mmlab/mmdetection3d/blob/8214a9779997ad3606a4830a7b718ba1bcfbf16d/mmdet3d/ops/roiaware_pool3d/src/points_in_boxes_cuda.cu#L28).

Then the output is 

```python
tensor([[-1, -1,  0, -1,  0, -1, -1, -1]], device='cuda:0', dtype=torch.int32)
```

which is the correct behaviour under the LIDAR coordinate system defined in the [docstring](https://github.com/open-mmlab/mmdetection3d/blob/8214a9779997ad3606a4830a7b718ba1bcfbf16d/mmdet3d/core/bbox/structures/lidar_box3d.py#L13).

**Comment by THU17cyz** [comment]
Closed due to inactivity. 

p.s. A refactor is ongoing now.

**Comment by THU17cyz** [comment]
Just updated the docstrings to correctly describe the current coordinate systems.
