### ISSUE TITLE
Why hacking yaw is needed in KittiDataset

### ISSUE THREAD

**Issue by Xianpeng919** [open-mmlab/mmdetection3d#407]
Hello,

I wonder why the hack of yaw ([line616](https://github.com/open-mmlab/mmdetection3d/blob/d055876a2a88385e38673d5133865d211282c1d4/mmdet3d/datasets/kitti_dataset.py#L616)) is needed. If my predicted box is CameraInstanceBoxes, is the -np.pi needed?

**Comment by xiliu8006** [comment]
Because of the [get_direction_target](https://github.com/open-mmlab/mmdetection3d/blob/d055876a2a88385e38673d5133865d211282c1d4/mmdet3d/models/dense_heads/train_mixins.py#L317) function,  in this [line](https://github.com/open-mmlab/mmdetection3d/blob/d055876a2a88385e38673d5133865d211282c1d4/mmdet3d/models/dense_heads/train_mixins.py#L335-L336) we got the opposite direction to the KITTI dataset. Therefore we need the hack of yaw ([line616](https://github.com/open-mmlab/mmdetection3d/blob/d055876a2a88385e38673d5133865d211282c1d4/mmdet3d/datasets/kitti_dataset.py#L616)). We are fixing this problem

**Comment by Xianpeng919** [comment]
Thank you very much!
