### ISSUE TITLE
Question about point_in_box function

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection3d#410]
It seems there is a potential bug in ``point_in_box`` function, of which the main logics are from L24 to L49.
https://github.com/open-mmlab/mmdetection3d/blob/d055876a2a88385e38673d5133865d211282c1d4/mmdet3d/ops/roiaware_pool3d/src/points_in_boxes_cuda.cu#L24-L49

Take an example below: a box of ``[0, 0, 0, 4, 1, 0, pi/4]`` and a point of ``[1, 1]``. It is clear that the point is inside the box.
![167389085_128537309235456_4646916731233408965_n](https://user-images.githubusercontent.com/20570053/113590707-ec993f80-966d-11eb-807d-5a492ed1fc6d.jpg)

I rewrite a simple code to test the logics (z axis is ignore). ``ix_fixed = False`` indicate the original ``point_in_box `` logic. Here, I need to use ``-rot_angle`` to perform coord system transformation to get correct output. Feel free to have a look. 

```
import numpy as np

box = np.array([0, 0, 0, 4, 1, 0, np.pi / 4])
point = np.array([1, 1, 0])

def point_in_lidar_box(point, box, is_fixed=False):
    rot_angle = box[6] + np.pi / 2
    if is_fixed:
        rot_angle = -rot_angle
    cosa = np.cos(rot_angle)
    sina = np.sin(rot_angle)
    local_x = point[0] * cosa + point[1] * (-sina)
    local_y = point[0] * sina + point[1] * cosa

    w = box[3]
    l = box[4]
    in_flag = (local_x > -l / 2.0) & (local_x < l / 2.0) & (local_y > -w /2.0) & (local_y < w / 2.0)
    return in_flag

print(point_in_lidar_box(point, box, False))
print(point_in_lidar_box(point, box, True))

```

**Comment by THU17cyz** [comment]
Hi @thangvubk ,

Yes, this function does not agree with the definition of the LIDAR coordinate system described in the [docstring](https://github.com/open-mmlab/mmdetection3d/blob/8214a9779997ad3606a4830a7b718ba1bcfbf16d/mmdet3d/core/bbox/structures/lidar_box3d.py#L13). This is actually a legacy issue because earlier we follow the coordinate system in [SECOND](https://github.com/traveller59/second.pytorch#concepts). Please refer to #315 for more details. With some hard coding, the performance of models on KITTI doesn't get affected. Sorry for the inconvenience.

A refactor to unify these functions and the coordinate system is ongoing. Please stay tuned.
