### ISSUE TITLE
GPU Usage during evaluation (during training)

### ISSUE THREAD

**Issue by Divadi** [open-mmlab/mmdetection3d#456]
When evaluation is performed during a training cycle (say after an epoch), I have noticed that the GPU usage remains very high. 

For instance, if during training I have increased the batch size so GPU memory is close to 100%, the GPU memory usage as shown on nvidia-smi does not decrease at all during inference for validation.

This ended up being an issue when I used the KITTI evaluation script
https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/evaluation/kitti_utils/eval.py
which utilizes GPU for computing rotated iou (it then threw an out of cuda memory error).
I have tried increasing num_parts here
https://github.com/open-mmlab/mmdetection3d/blob/237cebffd80a25b46d0ff76eff9925d800c997d0/mmdet3d/core/evaluation/kitti_utils/eval.py#L341
to try to decrease GPU usage of evaluation, but it still runs out of memory as GPU memory usage is like 99%.

I was wondering why the GPU memory is so high during validation (when I do test.py, it is very low), and possible workarounds to this issue.

**Comment by Divadi** [comment]
Via here
https://github.com/open-mmlab/mmdetection/blob/187774ba35c077411cdc18da3bd1d41bb958628e/mmdet/apis/train.py#L135
It seems like the default evaluation (which I am using) is indeed batch size 1

**Comment by Wuziyi616** [comment]
Hi @Divadi, first thank you for your interest in our work. I think there are two possible workarounds to this issue.
1. Call `torch.cuda.empty_cache()` every time you end an epoch of training. This is will free GPU memory that is not occupied by tensors. I think you will see GPU memory decrease a lot after calling this.
2. Warp evaluate function with `with torch.no_grad():`. This will stop the network from computing gradients in evaluation and largely reduce GPU memory as well as speed up inference. An example is [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/test.py#L34-L35). I guess that's why test.py use low GPU memory.

**Comment by Wuziyi616** [comment]
It seems that `Runner` has already called `torch.no_grad():` over `val` function (see [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py#L57-L70)). Then I think you can try adding `torch.cuda.empty_cache()` to the first line of `val` function. Hope that will help.
