### ISSUE TITLE
Question about get_2d_boxes in kitti_converter.py

### ISSUE THREAD

**Issue by Xianpeng919** [open-mmlab/mmdetection3d#490]
Hello,

First, I want to thank you for your effort to push this area forward!

I wonder why loc_3d [[line]](https://github.com/open-mmlab/mmdetection3d/blob/e108340c79ff9fb13dedf883cb3746aab4b03250/tools/data_converter/kitti_converter.py#L431) is not using the location (or transformed center location) provided in KITTI labels? I see you add an offset to the original location. Why is the transformation needed?

**Comment by Tai-Wang** [comment]
It is because the labels provided by KITTI are in the coordinate of reference camera (camera 0). Instead, we would like to store them with the coordinates in the current camera (camera 2). There approximately exists an offset over the horizontal direction as shown in the KITTI [paper](http://www.cvlibs.net/publications/Geiger2013IJRR.pdf).
This error is limited for left RGB camera (compared to the adjacent camera 0) while significant for right cameras.

**Comment by Xianpeng919** [comment]
Got it. Thank you very much!
