### ISSUE TITLE
Van and truck class detection evaluation not good in pointpillars model training on kitti dataset 

### ISSUE THREAD

**Issue by mohamed11981198** [open-mmlab/mmdetection3d#505]
I want to train pointpillars model with (car,cyclist,perdestian ,van and truck) classes on kitti dataset but the evaluation on van and truck not good even the van number of samples is bigger than the cyclists number of samples wihch is good in evaluation and i use a additional anchor size for van and trucks is [2,12,3]

**Comment by Tai-Wang** [comment]
I have not trained models for van and truck detection on KITTI for a long time. In my memory the performance can be about 30-40% AP for van. What about you?

**Comment by mohamed11981198** [comment]
![image](https://user-images.githubusercontent.com/47197453/116703815-fc851480-a9ca-11eb-9be1-dbc5d0dc1bb6.png)

yes it give a low accuracy , in your opinion what's the best way to make the model detect other vehicles types like (bus,van ,trucks ..)

**Comment by Tai-Wang** [comment]
Apart from additional anchor sizes for reference, you also need to add new classes into the data augmentation (database sampler). You can basically compare the config for 3 classes and 1 class (only car) on KITTI and imitate the way of supporting more classes.

**Comment by mohamed11981198** [comment]
Okay i will try this ,thank you very much for your interest

**Comment by mohamed11981198** [comment]
Yes i did but the accuracy still low for trucks and van classes ,could be any other reason ؟

**Comment by Tai-Wang** [comment]
Maybe you can try with different anchor sizes like the [config](https://github.com/traveller59/second.pytorch/blob/master/second/configs/all.fhd.config) given in the second.pytorch. Actually, different categories in different datasets may need different anchor sizes because their definitions of van/truck and annotation criteria can be inconsistent. Also you can refer to that codebase for van/truck detection on KITTI. I could get about 40 AP for van when I used that code in my memory.

**Comment by Latha-13** [comment]
Hi @mohamed11981198  how do you evaluate the performace metrics can you give me that command i trying to evalute it for kitti dataset.

Thank you.
