### ISSUE TITLE
how to make np array translate to kitti dataset?

### ISSUE THREAD

**Issue by zoearthmoon** [open-mmlab/mmdetection3d#517]
hello~
i want to use 3D np array data to mmdetection3d
but i don't know how to make 3D np array to kitti dataset

is there any article can teach me how to do that?
thanks every one

**Comment by THU17cyz** [comment]
Hi @zoearthmoon ,

Can you state your question clearer and perhaps provide an example?

**Comment by zoearthmoon** [comment]
thank for your reply

for example
i want to use a np array like  3d_array = np.zeros((200, 200, 200))
and label is in the array center  

how to make the train data and label data ?
thanks for help~

**Comment by THU17cyz** [comment]
You should modify the get-data and get-annotation functions [here](https://github.com/open-mmlab/mmdetection3d/blob/b255d16b9f8a19a8f1065a1ae6c88fd2a03dc325/mmdet3d/datasets/kitti_dataset.py#L95) and [here](https://github.com/open-mmlab/mmdetection3d/blob/b255d16b9f8a19a8f1065a1ae6c88fd2a03dc325/mmdet3d/datasets/kitti_dataset.py#L138).

Note that in the get-data function we only get the path to the point cloud file, so you may also have to modify the point cloud loading pipeline [here](https://github.com/open-mmlab/mmdetection3d/blob/b255d16b9f8a19a8f1065a1ae6c88fd2a03dc325/mmdet3d/datasets/pipelines/loading.py#L328).

But I suggest you first separate the data and annotation instead of putting them in one numpy array.

**Comment by zoearthmoon** [comment]
hello ~ thank for your reply

actually i whant to use data is medical DICOM images
like human full body 3d data CT scan
and i label a tumor by a 3d box label

but i dont know how to change the 3D data and  3d box label to kitti dataset type.
and how to define the model input shape like (512 ,512, 64) ?

thanks for help again~

**Comment by THU17cyz** [comment]
1. I would recommend you to carefully examine the kitti dataset format and convert you data to the format before using them with our codebase, then you need not modify the data loading and preparation functions.
2. See https://github.com/open-mmlab/mmdetection3d/blob/master/docs/data_preparation.md
3. It samples ground truth annotations from all annotations based on class name, difficulty, point number in 3d box, etc.

**Comment by zoearthmoon** [comment]
hello ~ @THU17cyz  thank for your reply

i just cant understand the kitti data format

i have use coco dataset before
and coco dataset have complete teaching
like this vid
https://www.youtube.com/watch?v=h6s61a_pqfM

but...
i cant find the  complete teaching for kitti data format...
can you give me some suggest?

thank you~

**Comment by THU17cyz** [comment]
Unfortunately I don't know such tutorial. Maybe take a look at readme from https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_object.zip?

**Comment by Tai-Wang** [comment]
@zoearthmoon Yes you can basically follow the readme provided in the file recommended by @THU17cyz . [Here](http://www.cvlibs.net/publications/Geiger2013IJRR.pdf) is the original paper for KITTI dataset, which you can refer to for more details about some intrinsic settings of the cars for data collection.
