### ISSUE TITLE
Question about voxelization

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection3d#521]
[Voxelization class](https://github.com/open-mmlab/mmdetection3d/blob/b255d16b9f8a19a8f1065a1ae6c88fd2a03dc325/mmdet3d/ops/voxel/voxelize.py#L64) voxelizes point input of``xyz`` to ``zyx`` format. Is there any specific reason for this?

**Comment by Tai-Wang** [comment]
It's just a convention. An underlying reason can be we usually take the height channel (z-axis in LiDAR coordinates) as the feature channel. After all bird view projection is most consistent with 3D space in the driving scene (compared to other orthogonal projections from other views).

**Comment by thangvubk** [comment]
Thanks for your explanation. However, since mmdet3d support both Lidar and Depth point clouds, this convention exhibits some limitations when performing voxelization for Depth PC dataset like ScanNet.

**Comment by Tai-Wang** [comment]
It's a potential problem for different kinds of coordinates indeed. Currently because voxel-based methods are not suitable for indoor datasets, it will not affect any models up to now. If there is any need for this in the future, I would prefer to converting the depth points to LiDAR points before voxelization.
