### ISSUE TITLE
How to run imvotenet with kitti dataset?

### ISSUE THREAD

**Issue by daxiongpro** [open-mmlab/mmdetection3d#530]
The default config.py uses sun-rgbd dataset on imvotenet model. Now, I wish to run `imvotenet `with `kitti `dataset, how can I write the config file? And what other steps should I do?

**Comment by Tai-Wang** [comment]
Basically you can use kitti dataset configs to replace those for sun-rgbd dataset and also modify the imvotenet model config according to the setting of kitti dataset (maybe could refer to other models on KITTI).
But honestly that's really not trivial because 1) there are many different settings between these two datasets, you need to understand both of them exactly, 2) the paradigm of votenet maybe not exactly suitable for outdoor scenes due to the different distribution of indoor points and LiDAR points collected in real time even with much finetuning in terms of hyper-parameters.

**Comment by Wuziyi616** [comment]
I have discussed with someone who trained VoteNet on outdoor LiDAR scenes before and the performance is very bad. I don't think it's a good idea to do so. Maybe you can have a look at [this](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py) model which also uses 2D-3D multi-modality fusion on KITTI dataset.

**Comment by THU17cyz** [comment]
Yes VoteNet on KITTI has a very bad performance, personally I suggest not doing so.

**Comment by daxiongpro** [comment]
> I have discussed with someone who trained VoteNet on outdoor LiDAR scenes before and the performance is very bad. I don't think it's a good idea to do so. Maybe you can have a look at [this](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py) model which also uses 2D-3D multi-modality fusion on KITTI dataset.

I just want to learn how to write the config.py file. But there always make error when I use imvotenet model with kitti dataset. I just want to it trains success!
