### ISSUE TITLE
Some question about the evaluation on KITTI dataset

### ISSUE THREAD

**Issue by HilbertXu** [open-mmlab/mmdetection3d#555]
Hi,

Thanks for the amazing mmdetection3d which helps me a lot when I develop me own 3D detection method.
I have some general question about the evaluation part and wonder if I could get some help from here.
My 3D detection method predict 3D bounding box for each car instance the the whole scene, but few car instances have gt labels. Thus, those bounding boxes for unlabeled car instances are calculated as FP samples and leads to bad evaluation result. Could you please tell me how to modify my method and avoid such a situation?

Best regrads

**Comment by Wuziyi616** [comment]
Do you mean some car instances don't have corresponding GT boxes? Can you show some examples to help me better understand your questions?

**Comment by HilbertXu** [comment]
Hi @Wuziyi616 
here are some examples
red boxes are predictions, green boxes are gts
As you can see, my method predict bounding box for some car instance without gt labels
will they be calculated as FP samples and make the evaluation result worse?

![Screen Shot 2021-05-18 at 9 43 30 PM](https://user-images.githubusercontent.com/33152255/118663655-6f8fe700-b823-11eb-85a8-b0f87291ba18.png)
![Screen Shot 2021-05-18 at 9 44 04 PM](https://user-images.githubusercontent.com/33152255/118663667-7159aa80-b823-11eb-8b13-8b494d667a7d.png)

**Comment by Wuziyi616** [comment]
Hi, it seems indeed a problem to me. However, I am not very familiar with KITTI dataset (I personally am responsible for 3D Seg code). I am asking someone in our team and he may return to you soon.

**Comment by Wuziyi616** [comment]
I asked someone and they told me the KITTI dataset has some **truck** instances that are not used for training (we only use **car**). But I think the instances missed in your visualizations are indeed cars not trucks. Can you provide the data id of these results and I will look into it?

**Comment by HilbertXu** [comment]
Hi @Wuziyi616,

Thanks for your help!
the file ids of the above test result are 000019 and 000025

**Comment by Wuziyi616** [comment]
I did a quick visualization and I didn't miss that GT in data 000019 (shown below)
![snapshot00](https://user-images.githubusercontent.com/37072215/118759823-51b69680-b8a4-11eb-98ad-9d409c039741.png)


However in data 000025, the car in the left is indeed not annotated (shown below)
![snapshot00](https://user-images.githubusercontent.com/37072215/118759959-8de9f700-b8a4-11eb-9ca2-d9b10faaaef7.png)


I look into the raw data and find out that, the missed car's GT is not provided by KITTI. It's true that it will be regarded as FP and affect the evaluated performance. But everyone suffer from this and that's fair? Did you discover many such issues? Or maybe something is wrong with your code (e.g. I didn't miss that car in data 000019)?

Some reasons that a GT might be misses:
1. The number of points belonging to that instance is very small, and it's filtered out by our data pre-processing. These instances may seem obvious in image, but very sparse in LIDAR point cloud.
2. KITTI annotated GT in **LiDAR** point clouds rather than images, so some instances which are obvious in images might be hard to distinguish given only point cloud

Hope this can help you!

**Comment by HilbertXu** [comment]
Hi @Wuziyi616 ,

Sincerely thanks for your patience and help!
I am just wondering how to reduce the negetive influence comes from those unlabeled car instance. Cause I use semantic instance segmentation module to find car instances and predict bbox for each instance. Hence, there are lots of bounding boxes corresponding to unlabeled instance and they will be calculated as FP. Could you please give me some advice about how to improve and deal with such a situation?

Best regards

**Comment by Wuziyi616** [comment]
I don't think there is an easy way to achieve so because, after all, this issue is caused by the dataset. I suggest you to test some of our pre-trained models on KITTI, and see if they are also affected? If so, then the comparison is also fair I think?

Also I really don't think such missing GT is very common in KITTI. I may be wrong because I am not familiar with it.

**Comment by Wuziyi616** [comment]
Feel free to re-open this issue should you have any further questions :)
