### ISSUE TITLE
Testing the Kitti dataset

### ISSUE THREAD

**Issue by Latha-13** [open-mmlab/mmdetection3d#564]
Hi

Im currently using MMdetection3d for testing the Kitti dataset. I have prepared the dataset of kitty according to format specified as:
mmdetection3d
├── data
         ├── kitti
                 ├── ImageSets
                 ├── testing
                         ├── calib
                         ├── image_2
                         ├── velodyne
                 ├── training
                         ├── calib
                         ├── image_2
                         ├── label_2
                         ├── velodyne

1. After this should i need to run the "python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti" ?
2. After this what is the ouput produced in it?
3. Then for testing the kitti dataset whether i should run "python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] [--eval ${EVAL_METRICS}] [--show]" ?
4. Does for testing the kitti dataset we need GroundTruth  information ?

Kindly, help me in understanding the concept what MMdetection3d does.

Thank you.

**Comment by THU17cyz** [comment]
Hi @Latha-13,

1. Yes, you should run this command.
2. `kitti_gt_database`, `kitti_infos_xxx.pkl`, `kitti_dbinfos_train.pkl` will appear under `data/kitti`.
3. Yes. If you are running on a headless machine, do not add `--show`.
4. For testing we do not need GT, because we don't have them. You should submit the predictions to the test server. Please refer to [this](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html#test-existing-models-on-standard-datasets).

**Comment by tojimahammatov** [comment]
Hi @Latha-13 , I hope you have seen [doc](https://mmdetection3d.readthedocs.io/en/latest/) page of mmdetection3d. In Quick Run you can find examples for training and testing with single vs multiple GPUs. 
Answers for your questions:
1. yes, if you put everything as shown [here](https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html), the script does the rest.
2. then you will have *.pkl files in your data directory (./data/kitti/). Those files are used during training. you can assume this as a data pre-processing stage.
3. if you have pretrained checkpoints, weights then you can go for testing. But I think you want to train first, since previous case was data pre-processing, now you can do training. Check [here](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html). Note that, tools/test.py is for testing, train.py is for training, and there are dist_train.sh as well.
4. dataset contains validation Ground-truth labels. For test set no.

**Comment by THU17cyz** [comment]
Actually, by default when we test KITTI we mean validate, see [here](https://github.com/open-mmlab/mmdetection3d/blob/4af2144c5cde0788a09d313eb8bc03c3e6ab7347/configs/_base_/datasets/kitti-3d-3class.py#L128). We have the ground truth for validation set.

**Comment by Latha-13** [comment]
Hi all
Thank you for your points in clearing my doubts.

Iam trying to test the kitty dataset in google collab, iam trying to test the kitty dataset for only 5 images, 5 veloydyne and 5 claibration data, when i tried to run create_dataset.py

!python create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti

**I got this error:**

Traceback (most recent call last):
  File "create_data.py", line 243, in <module>
    out_dir=args.out_dir)
  File "create_data.py", line 23, in kitti_data_prep
    kitti.create_kitti_info_file(root_path, info_prefix)
  File "/content/mmdetection-2.11.0/mmdetection3d/tools/data_converter/kitti_converter.py", line 101, in create_kitti_info_file
    train_img_ids = _read_imageset_file(str(imageset_folder / 'train.txt'))
  File "/content/mmdetection-2.11.0/mmdetection3d/tools/data_converter/kitti_converter.py", line 40, in _read_imageset_file
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/kitti/ImageSets/train.txt'

Does any one tried in google collab for testing the datasets , if so can you can anyone share the notebook for that for reference purposes.

**Comment by Latha-13** [comment]
Hi @tojimahammatov can you just say me how to calculate the peroformance metrics of kitti dataset?
and 
Why there is no .json file is created while testing the kitti dataset? I got only the obj files alone.

**Comment by tojimahammatov** [comment]
@Latha-13 , performance metrics of kitti is just 3D box overlap, similar to IoU. More info is given [here](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d). 

It seems you are a bit lazy to read docs )) . [Here](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html) is shown how to generate .json file as well. When you test a model you need to add the following options:

`--format-only --options 'jsonfile_prefix=./any_kitti_results_directory'`

**Comment by daxiongpro** [comment]
> Hi @tojimahammatov can you just say me how to calculate the peroformance metrics of kitti dataset?
> and
> Why there is no .json file is created while testing the kitti dataset? I got only the obj files alone.

I even cannot get obj file when I run ./tools/test.py. Do you know how to solve it?

**Comment by tojimahammatov** [comment]
@daxiongpro , hi, did you use ```--out /some_path/``` along with test.py command ? See the [docs and examples](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html).
