### ISSUE TITLE
Anyone have tried training PointPillars on indoor datasets, like scannet or sunrgbd?

### ISSUE THREAD

**Issue by neverrop** [open-mmlab/mmdetection3d#581]
Is it possible to just combine the data & model configs, and add some modifications, to get a good performance on rgbd dataset?

**Comment by Wuziyi616** [comment]
It is indeed possible to combine them to train PointPillars on indoor datasets, you can simply do it. But I don't think that will get a good performance because indoor point clouds are very different from outdoor ones. For example, outdoor point clouds are dense nearby but very sparse far away, while indoor point clouds is nearly uniform everywhere. Besides, indoor point clouds have complex information along height dim, while PointPillars compress the features into pillars that ignores height dim.

**Comment by THU17cyz** [comment]
The "Pillars" in its name means it's designed for outdoors point cloud for reasons explained by Wuziyi616.

**Comment by neverrop** [comment]
> It is indeed possible to combine them to train PointPillars on indoor datasets, you can simply do it. But I don't think that will get a good performance because indoor point clouds are very different from outdoor ones. For example, outdoor point clouds are dense nearby but very sparse far away, while indoor point clouds is nearly uniform everywhere. Besides, indoor point clouds have complex information along height dim, while PointPillars compress the features into pillars that ignores height dim.

Thanks for your reply. I see `shift_height` is already added for sunrgbd dataset, adding an extra height channel in input features, which might work better?. Also I've tried training PointPillars on indoor datasets, but got an error as described in https://github.com/open-mmlab/mmdetection3d/issues/605

**Comment by FabianSchuetze** [comment]
It was very interesting to read the discussion! What would your guess be how useful centerpoint with voxelnet as backbone is when working with sunrgbd?
