### ISSUE TITLE
Point cloud range info

### ISSUE THREAD

**Issue by selmadeac** [open-mmlab/mmdetection3d#644]
Hi! I noticed the point cloud range variable is different for SECOND and for POINTPILLARS when looking on kitti config files. For example, for SECOND it is: [0, -40, -3, 70.4, 40, 1] and for pointpillars: [0, -39.68, -3, 69.12, 39.68, 1]. If I try to change it and put a random number, the network does not train well. I get 0% mAP on all classes. Is it because the values are computed based on the given voxel_size?
And why is the max_voxels=(16000, 40000), and not just an integer? What does 40000 stand for?

**Comment by Wuziyi616** [comment]
Of course the random number won't work, because this limits the point cloud you will see. Those numbers are taken from their papers. They are basically some empirical number and not related to `voxel_size`.

As for the tuple input of `max_voxels`, it seems from [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/voxel/voxelize.py#L107-L110) that, the first value is used in training mode and the second value is used in testing mode. Please note that we will drop the remaining points if voxels number goes beyond `max_voxels` by voxelizing point clouds by `voxel_size`. So using a larger `max_voxels` during testing can keep more points and thus get better performance. You can refer to their paper for more details.
