### ISSUE TITLE
`ObjectNameFilter` not filtering by class names?

### ISSUE THREAD

**Issue by haotian-liu** [open-mmlab/mmdetection3d#645]
[`ObjectNameFilter`](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/transforms_3d.py#L784) by description in docstring indicates that it "Filter GT objects by their names." But it seems that it will only filter out the GT objects with min-k (k=len(classes)) categories instead of considering the class names?

Is there any misunderstanding here, and what is the actual usage / purpose of this function? Thanks.

**Comment by Wuziyi616** [comment]
Yes, your understanding is correct, we only keep `len(classes)` labels and boxes here. I agree that it doesn't behave like its function name, which is because we currently don't pass **class_name** to pipelines. Instead, we only have **class_idx** so we can only filter labels according to idx.

This function is only used in KITTI and nuScenes datasets in the current codebase. It won't cause a bug because we have already filtered class labels in the Dataset class's `get_ann_info` function. See nuScene [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/nuscenes_dataset.py#L272-L276) for example.
