### ISSUE TITLE
How to visualize the detection results of FCOS3D in bird eye view, like Fig.5 in paper?

### ISSUE THREAD

**Issue by xieenze** [open-mmlab/mmdetection3d#665]
Hi, 
Recently I read FCOS3D and want to visualize the result in bird eye view. But I cannot find the document about it.
How to generate the BEV detection results like Fig5 in the paper?

**Comment by Tai-Wang** [comment]
Thanks for your interest.
Fig. 5 in the paper is visualized based on the [nuScenes devkit](https://github.com/nutonomy/nuscenes-devkit). Because it needs the corresponding point cloud data, we do not support the BEV visualization in this codebase for monocular 3D detection. You can first refer to the visualization doc for drawing 3D boxes on the images.

**Comment by chuong98** [comment]
@xieenze Hi, I am interested in the same problem. Did you figure out how to do it ?
