### ISSUE TITLE
Confuse about offset in kitti_converter

### ISSUE THREAD

**Issue by lyuwenyu** [open-mmlab/mmdetection3d#712]
Hi, here i have a question about offset
It means transfer pos to camera_2 coord, right?

```
suppose pos<x, y, z, 1>
# P_2 @ pos

u = x * P_2[0, 0] + P_2[0, 3]

# after transfer
x_new = x + P_2[0, 3] / P_2[0, 0]
u = x_new * P_2[0, 0] ( x * P_2[0, 0] + P_2[0, 3] )
```

**BUT why minus P_0[0, 3] in code ?**

https://github.com/open-mmlab/mmdetection3d/blob/e108340c79ff9fb13dedf883cb3746aab4b03250/tools/data_converter/kitti_converter.py#L428

**Comment by Tai-Wang** [comment]
The offset is CAM2 compared to CAM0 in terms of 3D locations (typically info['calib']['P0'][0, 3] is 0). So it is basically equivalent to your x_new = x + P_2[0, 3] / P_2[0, 0].

When doing projection, we need to use the annotated location (`loc` instead of `loc_3d` in the code) that is in the CAM0/referenced camera coordinate to apply P2 matrix.

**Comment by lyuwenyu** [comment]
Got it~

Thanks
