### ISSUE TITLE
Train use "python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py"

### ISSUE THREAD

**Issue by stidk** [open-mmlab/mmdetection3d#715]
pytorch = '1.9.0'
cuda='10.2'
python = '3.7.10'
mmcv = 'cu102/torch1.9.0-1.3.8'
pycocotool='2.0.0'
numpy='1.19.5'
-----------------------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/train.py", line 223, in <module>
    main()
  File "tools/train.py", line 219, in main
    meta=meta)
  File "/home/customer/01_DK/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
    meta=meta)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/customer/01_DK/mmdetection3d/mmdet3d/models/detectors/base.py", line 58, in forward
    return self.forward_train(**kwargs)
  File "/home/customer/01_DK/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 90, in forward_train
    x = self.extract_feat(points, img_metas)
  File "/home/customer/01_DK/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 41, in extract_feat
    voxels, num_points, coors = self.voxelize(points)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
    return old_func(*args, **kwargs)
  File "/home/customer/01_DK/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 56, in voxelize
    res_voxels, res_coors, res_num_points = self.voxel_layer(res)
  File "/home/customer/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/customer/01_DK/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 113, in forward
    self.max_num_points, max_voxels)
  File "/home/customer/01_DK/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 53, in forward
    coors_range, max_points, max_voxels, 3)
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
-----------------------------------------------------------------------
Is my version of pytorch too high or other problems?Official website of mmcv have not the version of this.

**Comment by Wuziyi616** [comment]
This may be the problem because MMCV currently doesn't officially support torch1.9. Maybe you can try torch1.7 or lower (1.8 may also cause errors).

**Comment by stidk** [comment]
pytorch='1.6.0',cuda='10.1', mmcv='1.3.8'(pip install mmcv-full==1.3.8 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html),mmdet='2.14.0',mmsegmentation='0.14.1',numpy='1.19.5',pycocotools='2.0.0', mmdetection3d =the new one,have the same wrong.What about your environments or versions.

**Comment by Wuziyi616** [comment]
Try running `python mmdet3d/utils/collect_env.py` to show me your entire environment settings? My current environment is torch1.5.0, numpy 1.19.5, same mmcv, mmdet and mmseg as you and succeed.

**Comment by stidk** [comment]
sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
GPU 0: TITAN RTX
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.2
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.15.0+ea84601

**Comment by stidk** [comment]
Thank for your help,it have trained when i use torch='1.5.0',cuda='10.1'.

**Comment by Wuziyi616** [comment]
Glad it helps :)

**Comment by zhangsikui** [comment]
This is my environment
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.5.3
MMCV: 1.3.8
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.0
MMDetection: 2.14.0
MMSegmentation: 0.15.0
MMDetection3D: 0.15.0+1b2e64c
But there are still the same mistakes

**Comment by zhangsikui** [comment]
Do I need to change cuda version to 10.1??

**Comment by Wuziyi616** [comment]
@zhangsikui Yes. You can see that your cuda version is 10.0 but your pytorch is compiled with 10.1. So you can upgrade cuda to 10.1. Or you can also install a pytorch compiled with cuda10.0.

**Comment by zhangsikui** [comment]
Thank you for your answer, browsing the comment area and reading your email. I should need to upgrade to CUDA10.1. I am trying.
Thank you very much.



---Original---
From: "Ziyi ***@***.***&gt;
Date: Sat, Jul 24, 2021 23:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection3d] Train use "python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py" (#715)




 
@zhangsikui Yes. You can see that your cuda version is 10.0 but your pytorch is compiled with 10.1. So you can upgrade cuda to 10.1. Or you can also install a pytorch compiled with cuda10.0.

**Comment by scar-on** [comment]
I'm sorry to bother you again, refer to your solution. It still reports the same error when it runs demo.
Is it because of other mistakes？

#####
/home/cdutzj/scar/mmdetection3d/mmdetection/mmdet/core/anchor/builder.py:16: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
&nbsp; '``build_anchor_generator`` would be deprecated soon, please use '
Use load_from_local loader
Traceback (most recent call last):
&nbsp; File "/home/cdutzj/scar/mmdetection3d/demo/demo_api.py", line 11, in <module&gt;
&nbsp;&nbsp;&nbsp; result, data = inference_detector(model, point_cloud)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/apis/inference.py", line 115, in inference_detector
&nbsp;&nbsp;&nbsp; result = model(return_loss=False, rescale=True, **data)
&nbsp; File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
&nbsp;&nbsp;&nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
&nbsp;&nbsp;&nbsp; return old_func(*args, **kwargs)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/base.py", line 60, in forward
&nbsp;&nbsp;&nbsp; return self.forward_test(**kwargs)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/base.py", line 41, in forward_test
&nbsp;&nbsp;&nbsp; return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 99, in simple_test
&nbsp;&nbsp;&nbsp; x = self.extract_feat(points, img_metas)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 41, in extract_feat
&nbsp;&nbsp;&nbsp; voxels, num_points, coors = self.voxelize(points)
&nbsp; File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
&nbsp;&nbsp;&nbsp; return func(*args, **kwargs)
&nbsp; File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
&nbsp;&nbsp;&nbsp; return old_func(*args, **kwargs)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 56, in voxelize
&nbsp;&nbsp;&nbsp; res_voxels, res_coors, res_num_points = self.voxel_layer(res)
&nbsp; File "/home/cdutzj/anaconda3/envs/mmd3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
&nbsp;&nbsp;&nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 113, in forward
&nbsp;&nbsp;&nbsp; self.max_num_points, max_voxels)
&nbsp; File "/home/cdutzj/scar/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 53, in forward
&nbsp;&nbsp;&nbsp; coors_range, max_points, max_voxels, 3)
RuntimeError: CUDA error: invalid device function
段错误 (核心已转储
####
My environment is
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
&nbsp; - GCC 7.3
&nbsp; - C++ Version: 201402
&nbsp; - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
&nbsp; - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
&nbsp; - OpenMP 201511 (a.k.a. OpenMP 4.5)
&nbsp; - NNPACK is enabled
&nbsp; - CPU capability usage: AVX2
&nbsp; - CUDA Runtime 10.1
&nbsp; - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
&nbsp; - CuDNN 7.6.3
&nbsp; - Magma 2.5.2
&nbsp; - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.5.3
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.14.0
MMSegmentation: 0.15.0
MMDetection3D: 0.15.0+1b2e64c



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月24日(星期六) 晚上11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection3d] Train use "python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py" (#715)





 
@zhangsikui Yes. You can see that your cuda version is 10.0 but your pytorch is compiled with 10.1. So you can upgrade cuda to 10.1. Or you can also install a pytorch compiled with cuda10.0.
