### ISSUE TITLE
How to freeze parameters when training？

### ISSUE THREAD

**Issue by speshowBUAA** [open-mmlab/mmdetection3d#754]
I want to add a new branch to a well-pretrained model and preserve the parameters of the original model. How to set "requires_grad = False" in an elegant way?I want to add a new branch to a well-pretrained model and preserve the parameters of the original model. How to set "requires_grad = False" in an elegant way?

**Comment by Wuziyi616** [comment]
A workaround is to set the `lr` of these params to be 0. You can achieve this through `paramwise_cfg` in config files' `optimizer` args. See [this](https://github.com/open-mmlab/mmdetection/blob/5f6134796ed07f443d1bf389f57d3cee40bbd044/configs/yolof/yolof_r50_c5_8x8_1x_coco.py#L68) for example.

Let's say if you want to freese the parameters in `self.backbone`, you can set:
```
optimizer = dict(
    ...
    paramwise_cfg=dict(custom_keys={'backbone': dict(lr_mult=0.0)}))
```
so that the `lr` of params in backbone will be multipled by `0.0`, so their `lr` becomes `0` and won't be updated.

**Comment by Wuziyi616** [comment]
MMCV doesn't have an elegant way to set `requires_grad=False`, unfortunately. You can adopt this workaround for a while I believe.

**Comment by speshowBUAA** [comment]
Thx, I appreciate it very much.

**Comment by Agito555** [comment]
> A workaround is to set the `lr` of these params to be 0. You can achieve this through `paramwise_cfg` in config files' `optimizer` args. See [this](https://github.com/open-mmlab/mmdetection/blob/5f6134796ed07f443d1bf389f57d3cee40bbd044/configs/yolof/yolof_r50_c5_8x8_1x_coco.py#L68) for example.
> 
> Let's say if you want to freese the parameters in `self.backbone`, you can set:
> 
> ```
> optimizer = dict(
>     ...
>     paramwise_cfg=dict(custom_keys={'backbone': dict(lr_mult=0.0)}))
> ```
> 
> so that the `lr` of params in backbone will be multipled by `0.0`, so their `lr` becomes `0` and won't be updated.

In addition, this way of freezing is not the real way to freeze some layers, because running mean and std of BN in these layers still can change. For someone who care, see [it](https://blog.csdn.net/qq_39967751/article/details/123188763) in detail.

Want to know if there is solution which can really freeze layers for mmdet3D now?

**Comment by maxiuw** [comment]
maybe not the most elegant solution but i just added this to my model class and seems to be working fine :)

```
def freeze(self):
        if self.freeze_img:
            if self.with_img_backbone:
                for param in self.img_backbone.parameters():
                    param.requires_grad = False
```
