### ISSUE TITLE
A question about BackgroundPointsFilter

### ISSUE THREAD

**Issue by Physu** [open-mmlab/mmdetection3d#756]
In [https://github.com/open-mmlab/mmdetection3d/blob/78f456216f101b5b684db754176e0def17ab9d49/mmdet3d/datasets/pipelines/transforms_3d.py#L1139](url), why change the enlarge gt LiDAR boxes center to "gravity_center"? 
When we finally get the predictions, the center predictions are located at top center of the LiDAR box, e.g. the "gravity_center".
But I don't understand when we filter out the backgroud points, why we lift the center to top center(gravity center). In this way, we will not filter out the surrounding backgroud points below the original LiDAR box center.
![image](https://user-images.githubusercontent.com/32857082/125776223-850e9952-2514-4e56-b7e6-ef39a0215005.png)
When we keep the foreground points, the finally retained points  are just as you see above.
Would it be ok? if we just filter out the points above original LiDAR boxes center, and neglect the surrounding points which are below the original center?

**Comment by Wuziyi616** [comment]
`BackgroundPointsFilter` function calculates two masks, which identify points within `gt_bboxes_3d_np` and `enlarged_gt_bboxes_3d`. Then the points inside `enlarged_gt_bboxes_3d` while outside `gt_bboxes_3d_np` are neglected, so we are able to remove surrounding points which lie in this `enlarge_range` margin.

As for your question, we use gravity center [here](https://github.com/open-mmlab/mmdetection3d/blob/78f456216f101b5b684db754176e0def17ab9d49/mmdet3d/datasets/pipelines/transforms_3d.py#L1172) simply because [this](https://github.com/open-mmlab/mmdetection3d/blob/78f456216f101b5b684db754176e0def17ab9d49/mmdet3d/datasets/pipelines/transforms_3d.py#L1177) function `points_in_rbbox` requires the first three dim of input `rbbox` to be the gravity center (0.5, 0.5, 0.5). It doesn't mean we neglect `points below original center`.

Actually when looking into your issue, I find a bug in the code. We should input `origin=(0.5, 0.5, 0.5)` to function `points_in_rbbox`. Thanks for helping me find it out.

**Comment by Wuziyi616** [comment]
I think you can look into the function `points_in_rbbox` and you will know lifting to gravity center is just because it's required by this function.

**Comment by Physu** [comment]
@Wuziyi616  feel very happy to get response from you and be helpful! Thanks for your extraordinary work!
I will read the function code you mentioned above, hope find something fun and will share it in there.
By the way, sincerely hope you can give some advice about issue #612 , there is a lot of confusion about the performance.
I just don't know what methods or tricks should be executed to get a performance as Benchmark performance, e.g. the test set results in KITTI 3D object detection.
Thanks again!
