### ISSUE TITLE
How is the GPU vs CPU tensor management done?

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#758]
Hi. I have trouble understanding how and when do you send tensors to the GPU. I have a custom training routine where I use your dataloader and some modules using the build_X methods. When the data comes from your dataloaders, neither the data nor the model is required to be in the GPU. The tensors must be in the CPU for the modules to handle, which otherwise will raise an error of mismatched memory allocation for input and model. For example, for an Anchor3dHead, the passed tensor is sent through a Conv2d layer (https://github.com/open-mmlab/mmdetection3d/blob/78f456216f101b5b684db754176e0def17ab9d49/mmdet3d/models/dense_heads/anchor3d_head.py#L150), and I cannot find anywhere along the way any .to(device) or .cuda(). Yet, the processing seems really fast. Can you give me some insights on how is this done?

**Comment by Wuziyi616** [comment]
All the fundamental operations, e.g. training, data loading, model construction is handled via [**MMCV**](https://github.com/open-mmlab/mmcv). Let's take a Detector trained for several epochs using multi-GPUs distributed training for example:

1. We construct a `epoch_based_runner` for model training, each train/val step is performed inside it.
2. In a `epoch_based_runner`, we train each step via [this line](https://github.com/open-mmlab/mmcv/blob/366c628a85daf71fa26f652b402277c90d9f7d6e/mmcv/runner/epoch_based_runner.py#L50).
3. Move one step further, it leads to [here](https://github.com/open-mmlab/mmcv/blob/366c628a85daf71fa26f652b402277c90d9f7d6e/mmcv/runner/epoch_based_runner.py#L29) and [here](https://github.com/open-mmlab/mmdetection/blob/475c6bec197e6b495d48146636301590165d8f66/mmdet/models/detectors/base.py#L210).
4. Note that the Detector is wrapped inside a [`MMDistributedDataParallel`](https://github.com/open-mmlab/mmcv/blob/366c628a85daf71fa26f652b402277c90d9f7d6e/mmcv/parallel/distributed.py#L13) (which is similar to torch's `DistributedDataParallel`). The model is wrapped [here](https://github.com/open-mmlab/mmdetection/blob/475c6bec197e6b495d48146636301590165d8f66/mmdet/apis/train.py#L78) so that it's put to GPU.
5. Finally we got [this line](https://github.com/open-mmlab/mmcv/blob/366c628a85daf71fa26f652b402277c90d9f7d6e/mmcv/parallel/distributed.py#L51), which put data to GPUs as well.

I think this answers your question. Because our model and data are not explicitly converted to GPU, but they are done in some basic inner modules. Other conditions (`iter_based_runner`, single GPU training) is similar, where MMCV is used to perform these fundamental operations.

**Comment by AfonsoSalgadoSousa** [comment]
Thanks for the prompt response. I am not using your training routine at tools/train.py, but my custom training file. I build your modules with the corresponding build_X functions. Namely, I use an image backbone and a point cloud backbone (with build_backbone(my_custom_config)) and a dense head (build_head()). These should be standalone modules on the CPU, or am I mistaken?

**Comment by Wuziyi616** [comment]
Yes, if you only build them, they should only be on CPU. (You can simply check them using `pdb`)
