### ISSUE TITLE
Why minus pi/2 in yaw?

### ISSUE THREAD

**Issue by yangxpeijiu** [open-mmlab/mmdetection3d#778]
mmdet3d/core/bbox/structures/utils, in mono_cam_box2vis function.
```python
    # convert yaw by (-yaw - np.pi / 2)
    # this is because mono 3D box class such as `NuScenesBox` has different
    # definition of rotation with our `CameraInstance3DBoxes`
     yaw = -yaw - np.pi / 2
```

I am confused by what means of different definition of rotation with these two boxes?

**Comment by Tai-Wang** [comment]
It is a legacy issue due to hack of yaw and dimensions in the monocular 3D detection on nuScenes. Basically it is because the [rotation definition](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L548) of nuscenes box class is different from our `CameraInstanceBoxes`. It has been fixed with #744 . This function will be deprecated soon.
