### ISSUE TITLE
The huge difference between the results of the pointpillars model on nuscenes and waymo

### ISSUE THREAD

**Issue by WindZu** [open-mmlab/mmdetection3d#885]
What is the difference between model `hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-car` and `hv_pointpillars_secfpn_sbn-all_4x8_2x_nus-3d` in the input data. 

I input the same point cloud data with four dimensions (x y z intensity). 

For model `hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-car` that requires five dimensions, I fill the fifth dimension with 0, but the result is very poor. The results of the nuscene model are better.

But according to the results you provided, waymo has more  high mAPs although they use different data sets,

**Comment by Tai-Wang** [comment]
The points collected by different LiDARs are quite different in terms of distribution and intensities or other properties. So given a new point cloud, no current methods can not guarantee the results are satisfactory. For example, point clouds of nuScenes and Waymo are quite different because nuScenes uses 10-frame 32-line lidar points while Waymo uses 64-line points. Intensities of points collected by these two datasets are also quite different.
