### ISSUE TITLE
Order of class_names in Waymo vs anchors

### ISSUE THREAD

**Issue by Divadi** [open-mmlab/mmdetection3d#931]
**Describe the bug**
Looking at the waymo config
https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-3class.py
Then at the referenced base configs, it seems like the order of the anchors are mismatched w.r.t the order of class names?
https://github.com/open-mmlab/mmdetection3d/blob/2efdb6b6d94fb7ce944e83f743b98b1563e96fee/configs/_base_/models/hv_pointpillars_secfpn_waymo.py#L45-L56
https://github.com/open-mmlab/mmdetection3d/blob/2efdb6b6d94fb7ce944e83f743b98b1563e96fee/configs/_base_/datasets/waymoD5-3d-3class.py#L13
I noticed this when I tried training waymo by copy-pasting from these configs (much lower compared to SECOND, which has Cyclist and Pedestrian anchors flipped)
https://github.com/open-mmlab/mmdetection3d/blob/2efdb6b6d94fb7ce944e83f743b98b1563e96fee/configs/second/hv_second_secfpn_sbn_2x16_2x_waymoD5-3d-3class.py#L10
https://github.com/open-mmlab/mmdetection3d/blob/2efdb6b6d94fb7ce944e83f743b98b1563e96fee/configs/_base_/models/hv_second_secfpn_waymo.py#L33-L54

I apologize if I am in error - is there something I overlooked by any chance

**Comment by Tai-Wang** [comment]
It should do not matter because the class `AlignedAnchor3DRangeGenerator` with default `assign_per_class=False` do not care about the order of anchors and classes. The order should be particularly taken care of when applying `AlignedAnchor3DRangeGeneratorPerCls` in SSN. Have you ever tried with the order flipped and the results appear to be better?
I think the lower performance on Pedestrian and Cyclist is due to the worse capability of detecting small objects with PointPillars, which has coarser partition of 3D space than SECOND.

**Comment by Divadi** [comment]
Ah I understand - I missed that
I can try with the order flipped later
