### ISSUE TITLE
inference result can be saved as .json

### ISSUE THREAD

**Issue by fellenB** [open-mmlab/mmdetection3d#961]
Is there interface to save the inference result as json file?

**Comment by THU17cyz** [comment]
Hi @fellenB ,

Thanks for your interest. You may refer to https://github.com/open-mmlab/mmdetection3d/blob/master/docs/1_exist_data_model.md.

**Comment by fellenB** [comment]
> Hi @fellenB ,
> 
> Thanks for your interest. You may refer to https://github.com/open-mmlab/mmdetection3d/blob/master/docs/1_exist_data_model.md.

There is no instruction about the save format in the doc.

**Comment by ZCMax** [comment]
Hi, @fellenB ,
For now, we don't support save the inference result into .json format, but we support transfer training data into coco .json format in monocular 3D detection method, Your can refer to https://github.com/open-mmlab/mmdetection3d/blob/master/tools/create_data.py  source code to see how we transfer training data and label into coco .json format for training.
The whole process in our code can be:
First, convert kitti original data into .pkl format, then convert the .pkl format into .json format.

Since we support saving the inference results into .pkl format, You can refer to our code to write a script to convert the inference data into .json format.

**Comment by fellenB** [comment]
Thank you very much@ZCMax
